// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu12vpScj3SKHXB-lHP-JEoRRRFuIHlN8',
    appId: '1:783809958520:android:cfd5a49e96811013d7d38d',
    messagingSenderId: '783809958520',
    projectId: 'smart-dusty',
    databaseURL: 'https://smart-dusty-default-rtdb.firebaseio.com',
    storageBucket: 'smart-dusty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUTjBHnP7quln52qAR4H_xyT3ypPIhgLE',
    appId: '1:783809958520:ios:f922ba80254947c6d7d38d',
    messagingSenderId: '783809958520',
    projectId: 'smart-dusty',
    databaseURL: 'https://smart-dusty-default-rtdb.firebaseio.com',
    storageBucket: 'smart-dusty.appspot.com',
    androidClientId: '783809958520-lglhlt2evhc0kkts5plgbcjojg5lp77q.apps.googleusercontent.com',
    iosClientId: '783809958520-rfd3cjlbs417tttsofq3urlamc4pcfbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartDustbinAdmin',
  );
}
